// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHM9lEE3YomSZvXbRcXdKhlGW-_HpDzeY',
    appId: '1:922825205086:web:8956fd8db0609764589bcf',
    messagingSenderId: '922825205086',
    projectId: 'redine-dc9f2',
    authDomain: 'redine-dc9f2.firebaseapp.com',
    storageBucket: 'redine-dc9f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAajwq3zR4-XklESdDE9xcKwwovalfAQ9g',
    appId: '1:922825205086:android:51be50f82a46ac87589bcf',
    messagingSenderId: '922825205086',
    projectId: 'redine-dc9f2',
    storageBucket: 'redine-dc9f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcoyIQWuuOeZoRA_kafL4Rdd3u2XrNe7o',
    appId: '1:922825205086:ios:f54571d7465e66de589bcf',
    messagingSenderId: '922825205086',
    projectId: 'redine-dc9f2',
    storageBucket: 'redine-dc9f2.firebasestorage.app',
    iosClientId: '922825205086-gjkv6uq5u4at1ve23s5jid616in8u6uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redineFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcoyIQWuuOeZoRA_kafL4Rdd3u2XrNe7o',
    appId: '1:922825205086:ios:f54571d7465e66de589bcf',
    messagingSenderId: '922825205086',
    projectId: 'redine-dc9f2',
    storageBucket: 'redine-dc9f2.firebasestorage.app',
    iosClientId: '922825205086-gjkv6uq5u4at1ve23s5jid616in8u6uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redineFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHM9lEE3YomSZvXbRcXdKhlGW-_HpDzeY',
    appId: '1:922825205086:web:7b5974616926407d589bcf',
    messagingSenderId: '922825205086',
    projectId: 'redine-dc9f2',
    authDomain: 'redine-dc9f2.firebaseapp.com',
    storageBucket: 'redine-dc9f2.firebasestorage.app',
  );

}